baseURL = ""
languageCode = "en-us"
title = "801 Labs"

[params]
  paypalLink = "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=BWV8WFGYAEECN&source=website"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 100

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 200
  
  [[menu.main]]
    parent = "about"
    name = "Contact"
    url = "/contact/"
    weight = 100

  [[menu.main]]
    parent = "about"
    name = "Events"
    url = "/events/"
    weight = 200

  [[menu.main]]
    parent = "about"
    name = "Location and Hours"
    url = "/location-and-hours/"
    weight = 300

  [[menu.main]]
    parent = "about"
    name = "Resources"
    url = "/resources/"
    weight = 400 

  [[menu.main]]
    name = "Volunteer"
    url = "/volunteer/"
    weight = 600

  [[menu.main]]
    identifier = "social"
    name = "Be Social"
    url = "/events/"
    weight = 800 
 
  [[menu.main]]
    parent = "social"
    name = "Go there"
    url = "/location-and-hours/"
    weight = 100
    pre = "<i class='fa fa-location-arrow'></i>"

  [[menu.main]]
    parent = "social"
    name = "Email us"
    url = "mailto:board@801labs.org"
    weight = 200
    pre = "<i class='fas fa-envelope'></i>"

  [[menu.main]]
    parent = "social"
    name = "Read our research"
    url = "https://research.801labs.org/"
    weight = 300
    pre = "<i class='fas fa-flask'></i>"

  [[menu.main]]
    parent = "social"
    name = "Meetup"
    url = "/events/"
    weight = 400
    pre = "<i class='fab fa-meetup'></i>"

  [[menu.main]]
    parent = "social"
    name = "Slack chat"
    url = "https://slack.801labs.org"
    weight = 500
    pre = "<i class='fab fa-slack'></i>"

  [[menu.main]]
    parent = "social"
    name = "IRC chat"
    url = "ircs://chat.freenode.net:6697/#dc801"
    weight = 600
    pre = "<i class='fa fa-hashtag'></i>"

  [[menu.main]]
    parent = "social"
    name = "Commit"
    url = "https://github.com/801labs/"
    weight = 700
    pre = "<i class='fab fa-github'></i>"

  [[menu.main]]
    parent = "social"
    name = "Watch classes"
    url = "http://www.youtube.com/c/801LabsSaltLakeCity"
    weight = 800
    pre = "<i class='fab fa-youtube'></i>"

  [[menu.main]]
    parent = "social"
    name = "FaceBook"
    url = "https://fb.me/801labs"
    weight = 900
    pre = "<i class='fab fa-facebook'></i>"

  [[menu.main]]
    parent = "social"
    name = "Twitter"
    url = "https://twitter.com/801labs"
    weight = 1100
    pre = "<i class='fab fa-twitter'></i>"
  
  [[menu.main]]
    name = "Research"
    url = "https://research.801labs.org"
    weight = 800 

  [[menu.main]]
    name = "Old Site"
    url = "https://old.801labs.org"
    weight = 900 

  
  [[menu.footer]]
    name = "Code Of Conduct"
    url = "/code-of-conduct/"
    weight = 100

  [[menu.footer]]
    name = "Terms"
    url = "/terms/"
    weight = 200
